let error_fn = fn () 3 + [];
handle error_fn() {
    error _ {
        continue with 4;
    }
}